# Generated by Django 2.2 on 2022-10-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20221018_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='available',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
